### ISSUE TITLE
Final Cleanup and Polish

### ISSUE THREAD

**Issue by TheThirdOne** [hackedu/maestro#16]
@zachlatta Feel free to add anything in here that you would like to have done before MVP

**Comment by zachlatta** [comment]
At this point just double checking to make sure all functionality works.

It'd be great if we could also get some better logging in there so it'll be easier to figure out what issues the students run into, but that's not a high priority.

**Comment by TheThirdOne** [comment]
Can you elaborate on how logging will help identify issues students are running into?

**Comment by zachlatta** [comment]
Sure! More than anything, if there's a bug that they run into on the
backend it'd be easier to diagnose with less ambiguous logs.

**Comment by TheThirdOne** [comment]
A configuration system. (For api keys, host location, etc)

**Comment by zachlatta** [comment]
Just reading from the environment for now will probably be fine for the configuration.
