### ISSUE TITLE
Maestro's current state

### ISSUE THREAD

**Issue by TheThirdOne** [hackedu/maestro#17]
The JS file containing the library is found at `examplehost.com/static/baton.js`

Once that file is executed, the global variable `maestro` which contains all of the module libraries will be ready. Any messages from the server that are not caught with callbacks will automatically be logged in the console.

Examples:
```
maestro.Twilio.recieveSms("*",function(e){ //recieve any incoming sms
  maestro.Twilio.makeCall(e.From,e.To,maestro.Twilio.twiml().play(e.Body)); //call back  playing any sound file in the message
  console.log("Calling",e.From,"from",e.To,"playing",e.Body)
});
```
Things Maestro doesn't have:
  - Any concept of a user, there will not be any security preventing one user from using anothers twilio number for example
  - Proper error reporting to users, it is currently very possible that an error with a request as minor as "+1number" vs "number" will not be reported

Modules:
  - Echo:
    - very simple module, probably not useful
    - Usage:
    ```
    Echo.echo("Text to echo back",function(reply){
      console.log(reply); //prints "Text to echo back"
    });
    ```
  - Giphy:
    - Image search
    - Look [here](https://github.com/Giphy/GiphyAPI) for more details
    - Usage:
    ```
    Giphy.command("search query,id, etc",function(giphyReply){
      console.log(giphyReply);
    });
    ```
    - Commands:
      - search
        - First param mapped to `q`
      - getById
        - If the first param is a string it is used on `/v1/gifs/<id>`
        - The first param can also be an array of ids `[id1,id2,id3]`
      - translate
        - First param mapped to `s`
      - random
        - First param mapped to `tag`
      - trending
        - Does not have a first parameter

  - Neutrino:
    - Currently unfinished
    - wraps the [neutrino api](https://www.neutrinoapi.com/api/)
    - The most useful commands would be Geocode Address and Geocode Reverse

  - Twilio:
    - SMS and calling
    - Wraps both the Twilio [Restful API](https://www.twilio.com/docs/api/rest) and the [TWIML API](https://www.twilio.com/docs/api/twiml)
    - Usage:
    ```
    Twilio.sendSms("to-number","from-number","body");
    
    Twilio.recieveSms("from-number",function(twilioResponse){ //from-number can also be "*" which allows all recieved messages to be used
      console.log(twilioResponse.Body); //prints the body of the text message
    });
    
    var twiml = Twilio.twiml();
    twiml.say("Hello World");
    twiml.pause(5); //if left empty it will default to 1
    twiml.play("http://here-and-now.info/audio/rickastley_artists.mp3");
    twiml.say("You can").pause().say("also link them together like this");
    
    Twilio.makeCall("to-number","from-number",twiml); //there is currently no callback option for this, but it would be fairly easy to make
    
    Twilio.recieveCall("from-number",twiml,function(e){ //this callback will be destroyed after the call is made
      console.log(e.CallStatus); //likely will print "in-progress"
    });
    ```

**Comment by zachlatta** [comment]
:+1:

**Comment by zachlatta** [comment]
Perhaps make this a file in the repo?

**Comment by jonleung** [comment]
@TheThirdOne, made some comments here where any line I added starts with a `=>`

https://gist.github.com/jonleung/25c662e3e76c4acf7188

**Comment by jonleung** [comment]
Closing because I have successfully reviewed this and synced up with @TheThirdOne about it.
