### ISSUE TITLE
Add concurrency to modules

### ISSUE THREAD

**Issue by TheThirdOne** [hackedu/maestro#6]
Multiple commands need to be able to be executed simultaneously.

**Comment by TheThirdOne** [comment]
This system need to be revised heavily to prevent crashing bugs

**Comment by zachlatta** [comment]
Was this reopened as a result of crashing?

**Comment by TheThirdOne** [comment]
The crashing was mostly a result of #10. But I made a quick  and dirty patch last night to prevent crashing due to unclosed channels; this is for a proper solution.
